<%
  # http://mislav.uniqpath.com/rails/branching-the-database-along-with-your-code/
  app = "noosfero"
  branch = `git symbolic-ref HEAD 2>/dev/null`.chomp.sub('refs/heads/', '')
  user = (`whoami`).gsub(/\W/, '')
#  suffix = `git config --bool branch.#{branch}.database`.chomp == 'true' ? "_#{branch}" : ""
%>
# PostgreSQL. Versions 7.4 and 8.x are supported.
#
# Install the ruby-postgres driver:
#   gem install ruby-postgres
# On Mac OS X:
#   gem install ruby-postgres -- --include=3D/usr/local/pgsql
# On Windows:
#   gem install ruby-postgres
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
development:
  adapter: postgresql
  encoding: unicode
  database: <%= "#{app}_#{branch}_development" %>
  template: template0
  username: <%= user %>
  password:
  schema_search_path: "dialoga,public"

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #  host: 127.0.0.1
  #  port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

# dialoga:
#   adapter: postgresql
#   port: 5432
#   database: hom
#   encoding: unicode
#   schema_search_path: dialoga
#   username: <%= user %>
#   password:
#   domains:
#     - hom.dialoga.gov.br
#     - hom.login.dialoga.gov.br
#     - hom.gestao.dialoga.gov.br

production:
  adapter: postgresql
  encoding: unicode
  database: <%= "#{app}_#{branch}_production" %>
  template: template0
  username: <%= user %>
  password:


test: &TEST
  adapter: postgresql
  encoding: unicode
  database: <%= "#{app}_#{branch}_test" %>
  template: template0
  username: <%= user %>
  password:

cucumber:
  <<: *TEST
